<p>&nbsp;</p>
<p>&nbsp;</p>
<div style="border-top:1px solid silver">
  <table width="100%">
    <tr>
      <td width="25%" valign="top">
        <ul>
          <li>Related Links
            <ul>
              <li><a href="http://dns-api.org/">DNS API - Online DNS lookup service</a></li>
              <li>Are you interested in low-cost Git-Backed DNS hosting?  <a href="http://steve.org.uk/contact/">Email me</a>.</li>
            </ul>
          </li>
        </ul>
      </td>
      <td width="25%" valign="top">
        <ul>
          <li>Author Links
            <ul>
              <li><a href="http://steve.org.uk/contact/">E-mail Me</a></li>
              <li><a href="http://blog.steve.org.uk/">Blog</a></li>
              <li><a href="https://twitter.com/Stolen_Souls">Twitter</a></li>
            </ul>
          </li>
        </ul>
      </td>
      <td width="25%" valign="top">

<script type="text/javascript">
/* <![CDATA[ */
    (function() {
        var s = document.createElement('script');
        var t = document.getElementsByTagName('script')[0];

        s.type = 'text/javascript';
        s.async = true;
        s.src = '//api.flattr.com/js/0.6/load.js?'+
                'mode=auto&uid=skx&language=sv_SE&category=text&button=compact';

        t.parentNode.insertBefore(s, t);
    })();
/* ]]> */
</script>

<p><a class="FlattrButton" href="http://dhcp.io/" description="Free Dynamic-DNS" title="Free Dynamic-DNS">Free Dynamic-DNS</a></p>
</td>
      <td width="25%" valign="top">
      <p><a href="https://twitter.com/share" class="twitter-share-button" data-lang="en"   data-via="Stolen_Souls" data-url="http://dhcp.io/">Tweet</a></p>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

      </td>
    </tr>
  </table>
</div>
