<div style="border-top:1px solid silver">
  <table width="100%">
    <tr>
      <td width="25%" valign="top"></td>
      <td width="25%" valign="top">
        <ul>
          <li>Related Links
            <ul>
              <li><a href="http://dns-api.org/">DNS API - Online DNS lookup service</a></li>
            </ul>
          </li>
        </ul>
      </td>
      <td width="25%" valign="top">
        <ul>
          <li>Author Links
            <ul>
              <li><a href="http://blog.steve.org.uk/">Blog</a></li>
              <li><a href="https://twitter.com/Stolen_Souls">Twitter</a></li>
            </ul>
          </li>
        </ul>
      </td>
      <td width="25%" valign="top"></td>
    </tr>
  </table>
</div>
