<p>&nbsp;</p>
<p>&nbsp;</p>
<div style="border-top:1px solid silver">
  <table width="100%">
    <tr>
      <td width="25%" valign="top">
        <ul>
          <li>Related Links
            <ul>
              <li><a href="https://dns-api.org/">Online DNS lookup service</a></li>
              <li><a href="https://dns-api.com/">Git-based DNS Hosting</a></li>
            </ul>
          </li>
        </ul>
      </td>
      <td width="25%" valign="top">
        <ul>
          <li>Author Links
            <ul>
              <li><a href="https://blog.steve.fi/">Blog</a></li>
              <li><a href="https://twitter.com/Stolen_Souls">Twitter</a></li>
            </ul>
          </li>
        </ul>
      </td>
      <td width="25%" valign="top">
        <ul>
          <li>Site Links
            <ul>
              <li><a href="/abuse/">Report Abuse</a></li>
              <li><a href="/feedback/">Leave Feedback</a></li>
          </ul>
          </li>
        </ul>
      </td>
      <td width="25%" valign="top">
<script type="text/javascript">
/* <![CDATA[ */
    (function() {
        var s = document.createElement('script');
        var t = document.getElementsByTagName('script')[0];

        s.type = 'text/javascript';
        s.async = true;
        s.src = '//api.flattr.com/js/0.6/load.js?'+
                'mode=auto&uid=skx&language=sv_SE&category=text&button=compact';

        t.parentNode.insertBefore(s, t);
    })();
/* ]]> */
</script>

      <p><a href="https://twitter.com/share" class="twitter-share-button" data-lang="en"   data-via="Stolen_Souls" data-url="https://dhcp.io/">Tweet</a></p>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<p><a class="FlattrButton" href="https://dhcp.io/" description="Free Dynamic-DNS" title="Free Dynamic-DNS">Free Dynamic-DNS</a></p>

      </td>
    </tr>
  </table>
</div>
